<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'GifCreator' => array($vendorDir . '/lunakid/anim-gif/src'),
);
