<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit183e82687ba592d8eaf2e44eb4739ba4
{
    public static $prefixesPsr0 = array (
        'G' => 
        array (
            'GifCreator' => 
            array (
                0 => __DIR__ . '/..' . '/lunakid/anim-gif/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit183e82687ba592d8eaf2e44eb4739ba4::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
