<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdb4a5dcfe9e8fd8f75d85ebddb07178d
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Cron\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Cron\\' => 
        array (
            0 => __DIR__ . '/..' . '/mtdowling/cron-expression/src/Cron',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdb4a5dcfe9e8fd8f75d85ebddb07178d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdb4a5dcfe9e8fd8f75d85ebddb07178d::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
